name: Scrape NFL Futures

# At 23:01UTC daily (09:01 Melbourne time).
on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "1 23 * * *"

jobs:
  update-nfl-futures:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      PROXY_URL: ${{ secrets.PROXY_URL }}
      PROXY_PORT: ${{ secrets.PROXY_PORT }}
      PROXY_USERNAME: ${{ secrets.PROXY_USERNAME }}
      PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Package Installation
        run: Rscript -e 'install.packages(c("remotes", "dplyr", "httr"))'
      - name: bettRtab Installation
        run: Rscript -e 'remotes::install_github("JaseZiv/bettRtab")'
      - name: Update futures
        run: Rscript -e 'source(file.path("R", "nfl_futures.R"), echo = TRUE)'
      - name: Commit
        run: |
          git config --global user.name 'JaseZiv'
          git config --global user.email 'jaseziv83@gmail.com'
          git add .
          git commit -m 'updating NFL futures' || echo "No changes to commit"
          git push || echo "No changes to commit"
