name: Scrape sports markets

# At 22:01UTC daily (08:01 AEST).
on:
  push:
    branches:
      - main
  schedule:
    - cron: "1 22 * * *"

jobs:
  update-markets-betting:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      PROXY_URL: ${{ secrets.PROXY_URL }}
      PROXY_PORT: ${{ secrets.PROXY_PORT }}
      PROXY_USERNAME: ${{ secrets.PROXY_USERNAME }}
      PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Package Installation
        run: Rscript -e 'install.packages(c("remotes", "dplyr", "stringr", "httr", "xml2", "piggyback"))'
      - name: bettRtab Installation
        run: Rscript -e 'remotes::install_github("JaseZiv/bettRtab")'
      - name: Update futures
        run: Rscript -e 'source(file.path("R", "update_markets.R"), echo = TRUE)'
